name: alignment_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bwa
  - samtools=1.20
  - bcftools=1.20
  - htslib=1.20
  - minimap2
  - blast
  - snippy=4.6.0 
  - snpeff=4
  - breseq
