name: autocycler_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9
  - lrge=0.1.3
  - flye
  - minimap2>=2.11
  - miniasm
  - minipolish
  - any2fasta
  - canu
  - nextdenovo
  - nextpolish
  - raven-assembler
  - bandage
  - dnaapler
  - samtools>=1.18
  - bcftools>=1.18
  - htslib>=1.18
  - fastp
  - polypolish
  - pypolca
  - bwa>=0.7.17
  - freebayes>=1.3.1,<1.3.7
