name: medaka_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - bcftools>=1.11
  - minimap2>=2.11
  - samtools>=1.11
  - tabix>=1.11
  - dnaapler
  - pip:
    - medaka
